SASPLabs-2-4/Controllers/CatalogController.cs
using LinqKit;
using SASPLabs_2_4.Models;
using SASPLabs_2_4.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SASPLabs_2_4.Controllers
{
    public class CatalogController : Controller
    {
        WaffleContext db = new WaffleContext();

        public ActionResult Catalog(string searchString, string sort)
        {
            List<Waffle> waffles = db.Waffles.ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                waffles = Search(searchString);
            }

            if (!string.IsNullOrEmpty(sort))
            {
                if (sort == "Имя")
                {
                    waffles = db.Waffles.OrderBy(a => a.Name).ToList();
                }
                else if (sort == "Производитель")
                {
                    waffles = db.Waffles.OrderBy(a => a.Maker).ToList();
                }
                else if (sort == "Цена")
                {
                    waffles = db.Waffles.OrderBy(a => a.Price).ToList();
                }
            }

            return View(waffles);
        }

        [HttpGet]
        public ActionResult Buy(int? id)
        {
            ViewBag.WaffleId = id;
            return View();
        }

        [HttpPost]
        public ActionResult Buy(Purchase purchase)
        {
            purchase.Date = DateTime.Now;
            Cart.Cart cart = (Cart.Cart)Session["Cart" + User.Identity.Name];
            if (cart!=null && cart.Lines.Count() > 0)
            {
                //List<Purchase> purchases = new List<Purchase>();
                foreach (var item in cart.Lines)
                {
                    purchase.WaffleId = item.Waffle.Id;
                    for (int i = 0; i < item.Quantity; i++)
                    {
                        //purchases.Add(purchase);
                        db.Purchases.Add(purchase);
                        db.SaveChanges();
                    }
                }
                PurchCartViewModel purchCartViewModel = new PurchCartViewModel { Purchase = purchase, Count = cart.Lines.Count() };
                cart.Clear();
                return View("BoughtAll", purchCartViewModel);
                //return RedirectToAction("BoughtAll", purchases);
            }
            else
            {
                db.Purchases.Add(purchase);
            }
            db.SaveChanges();
            return RedirectToAction("Bought", purchase);
        }

        [HttpGet]
        public ActionResult Bought(Purchase purchase)
        {
            return View(purchase);
        }

        private List<Waffle> Search(string searchString)
        {
            var predicate = PredicateBuilder.New<Waffle>(e => false);


            Category category = db.Categories.FirstOrDefault(a => a.Name == searchString);

            if (category != null)
            {
                predicate.Or(a => a.CategoryId == category.Id);
            }
            predicate.Or(a => a.Name == searchString);
            predicate.Or(a => a.Maker == searchString);
            if (Int32.TryParse(searchString, out int result1))
            {
                predicate.Or(a => a.Price == result1);
            }
            if (DateTime.TryParse(searchString, out DateTime result2))
            {
                predicate.Or(a => a.ShelfLife == result2);
            }

            return new List<Waffle>(db.Waffles.Where(predicate));

        }
    }
}

SASPLabs-2-4/Views/Catalog/Bought.cshtml
@{
    ViewBag.Title = "Bought";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model SASPLabs_2_4.Models.Purchase

<h2>Ваш заказ</h2>
<h3>№ заказа @Model.PurchaseId</h3>
<div>
    @Html.DisplayForModel()
</div>

SASPLabs-2-4/Views/Catalog/BoughtAll.cshtml
@{
    ViewBag.Title = "BoughtAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model SASPLabs_2_4.ViewModels.PurchCartViewModel



<h2>Ваш заказ</h2>
@if (Model.Count > 1)
{
    <h3>№ заказа(ов) @(Model.Purchase.PurchaseId-Model.Count) - @Model.Purchase.PurchaseId</h3>
}
else
{
    <h3>№ заказа @Model.Purchase.PurchaseId</h3>
}



<div>
    <p>Имя</p>
    @Html.DisplayFor(a => a.Purchase.Person)
    <br>
    <br>
    <p>Адрес</p>
    @Html.DisplayFor(a => a.Purchase.Address)
    <br>
    <br>
    <p>Email</p>
    @Html.DisplayFor(a => a.Purchase.Email)
    <br>
    <br>
    <p>Номер телефона</p>
    @Html.DisplayFor(a => a.Purchase.Phone)
    <br>
    <br>
    <p>Форма оплаты</p>
    @Html.DisplayFor(a => a.Purchase.WageType)
    <br />
</div>

SASPLabs-2-4/Views/Catalog/Buy.cshtml
@model SASPLabs_2_4.Models.Purchase
@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3>Форма оформления покупки</h3>
    @using (Html.BeginForm("Buy", "Catalog", FormMethod.Post))
    {
        <input type="hidden" value="@ViewBag.WaffleId" name="WaffleId" />
        <p>Введите свое имя</p>
        @Html.TextBoxFor(m => m.Person)
        @Html.ValidationMessageFor(a => a.Person)
        <br>
        <p>Введите свой адрес</p>
        @Html.TextAreaFor(m => m.Address)
        @Html.ValidationMessageFor(a => a.Address)
        <br>
        <p>Введите Email</p>
        @Html.TextBoxFor(m => m.Email)
        @Html.ValidationMessageFor(a => a.Email)
        <br>
        <p>Введите свой номер телефона</p>
        @Html.TextBoxFor(m => m.Phone)
        @Html.ValidationMessageFor(a => a.Phone)
        <br>
        <p>Выберите форму оплаты</p>
        @Html.RadioButtonFor(m => m.WageType, "Карта")
        <span>Карта</span> <br />
        @Html.RadioButtonFor(m => m.WageType, "Наличные")
        <span>Наличные</span> <br />
        @Html.RadioButtonFor(m => m.WageType, "Наложенным платежом")
        <span>Наложенным платежом</span> <br />
        @Html.ValidationMessageFor(a => a.WageType)
        <br>
        <input type="submit" value="Отправить" />
    }
</div>

SASPLabs-2-4/Views/Catalog/Catalog.cshtml
@{
    ViewBag.Title = "Catalog";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@model List<SASPLabs_2_4.Models.Waffle>

<div>
    <h3>Распродажа вафлей</h3>
    <br>
    <br>
    <form class="form-inline">
        @Html.TextBox("searchString")
        <input type="submit" value="Поиск">
    </form>
    <br>
    <form class="form-inline">
        <select name="sort" class="form-control">
            <option>Все</option>
            <option value="Имя">Имя</option>
            <option value="Производитель">Производитель</option>
            <option value="Цена">Цена</option>
        </select>
        <input type="submit" value="Сортировать">
    </form>
    <br>
    <table>
        <tr style="border-bottom: 2px solid gray;">
            <td><p>Название</p></td>
            <td><p>Производитель</p></td>
            <td><p>Картинка</p></td>
            <td><p>Срок годности</p></td>
            <td><p>Цена</p></td>
            <td></td>
        </tr>
        @foreach (var b in Model)
        {
            <tr>
                <td><p>@b.Name</p></td>
                <td><p>@b.Maker</p></td>
                <td><img width="50" height="50" src="@b.ImagePath" /></td>
                <td><p>@b.ShelfLife.ToShortDateString()</p></td>
                <td><p>@b.Price</p></td>
                <td><p><a href="/Catalog/Buy/@b.Id">Купить</a></p></td>
                <td><p><a href="/Cart/Add/@b.Id">Добавить в корзину</a></p></td>
            </tr>
        }
    </table>
</div>